base_title: 'Freedger'
deadline_warning: '2: Warning'
deadline_recommend: '3: Recommend'
deadline_expired: '1: Expired'
deadline_delay: 3
delete_confirm_msg: '本当に削除しますか?'
invalid_access_msg: '不正なアクセスです。'
guest_login_msg: 'ゲストとしてログインしますか?'